### PR TITLE
Fix index method name collisions

### LINKED ISSUE #2332: Index methods generating with duplicate names
**Describe the current behavior**

Currently, `makeUniqueIndexMethodName` function does not exactly makes unique name for function in the case where a resource has multiple similar named secret property

**Describe the improvement**
How should things be changed or improved?

Have some sort of map to check the names for a property, if already exists, add the index(number in order) 

**Additional context**
Encountered this while adding MachineLearning/WorkspacesCompute

### PR DESCRIPTION
**Pull request by theunrepentantgeek**
**What this PR does / why we need it**:

We are now encountering collisions with our generated index method names, caused by having multiple properties nested (via different paths) with the same name.

This PR uses parts of the full property path to the property to avoid collisions, as we discussed offline.

Closes #2332

**Special notes for your reviewer**:

Takes the preexisting `indexFunctionBuilderContext` type and converts it into a full abstraction for a property chain. The implementation is changed so that chains form a tree of (nearly) immutable references, both to keep memory use down and to allow disambiguation.

**How does this PR make you feel**:
gif

**If applicable**:
- [x] this PR contains tests

### CODE REVIEW

**Review by super-harsh — APPROVED** [review]

**Comment by matthchr** [comment]
I've also made changes here to resolve the issue raised by @majguo in #2330, and I suspect our changes are going to conflict. Let's sync up and determine what order to merge them in @theunrepentantgeek.

File: v2/tools/generator/internal/codegen/pipeline/export_controller_type_registrations.go [hunk 1]
```diff
@@ -117,67 +190,108 @@ func catalogSecretPropertyChains(def astmodel.TypeDefinition, definitions astmod
...
 	return identityVisit(this, it, ctx)
 }
 
-func makeUniqueIndexMethodName(
+func (chain *propertyChain) indexMethodName(
 	idFactory astmodel.IdentifierFactory,
 	resourceTypeName astmodel.TypeName,
-	propertyChain []*astmodel.PropertyDefinition,
 ) string {
 	// TODO: Technically speaking it's still possible to generate names that clash here, although it's pretty
```
Comment (matthchr) [inline v2/tools/generator/internal/codegen/pipeline/export_controller_type_registrations.go:259]: Remove this comment

File: v2/tools/generator/internal/codegen/pipeline/export_controller_type_registrations.go [hunk 2]
```diff
@@ -71,28 +72,100 @@ func ExportControllerResourceRegistrations(idFactory astmodel.IdentifierFactory,
...
+func ensureIndexPropertyPathsUnique(chains []*propertyChain) {
+	// First mark all the properties at the end of each chain as required
+	for _, chain := range chains {
+		chain.requiredForPropertyPath = true
+	}
+
+	// Look until either we have no collisions, or we can't resolve them
+	for {
+		// Look for collisions
+		collisions := make(map[string][]*propertyChain)
```
Comment (matthchr) [inline v2/tools/generator/internal/codegen/pipeline/export_controller_type_registrations.go:109]: This isn't actually `collisions`, is it? It contains the names of all chains including changes that didn't collide? Would this be more clear as `proposedNames` or something?

File: v2/tools/generator/internal/codegen/pipeline/export_controller_type_registrations.go [hunk 3]
```diff
@@ -71,28 +72,100 @@ func ExportControllerResourceRegistrations(idFactory astmodel.IdentifierFactory,
...
+		// For any collision we find, try to resolve it
+		pathsChanged := false
+		for _, collision := range collisions {
+			if len(collision) > 1 && tryResolvePropertyPathCollision(collision) {
+				pathsChanged = true
+			}
+		}
+
+		if !pathsChanged {
+			break
```
Comment (matthchr) [inline v2/tools/generator/internal/codegen/pipeline/export_controller_type_registrations.go:124]: Is this an error condition?

File: v2/tools/generator/internal/codegen/pipeline/export_controller_type_registrations.go [hunk 4]
```diff
@@ -117,67 +190,108 @@ func catalogSecretPropertyChains(def astmodel.TypeDefinition, definitions astmod
 }
 
 type indexFunctionBuilder struct {
-	propChains [][]*astmodel.PropertyDefinition
+	propChains []*propertyChain
 }
 
-type indexFunctionBuilderContext struct {
-	props []*astmodel.PropertyDefinition
+// propertyChain represents an immutable chain of properties that can be used to index a secret on a resource. Each
```
Comment (matthchr) [inline v2/tools/generator/internal/codegen/pipeline/export_controller_type_registrations.go:196]: `immutable` here threw me because you changed `requiredForPropertyPath` and I kept trying to figure out how this is immutable given that.

I _think_ you mean that the chain part of it is immutable... but wondering if it would be clearer if you just dropped the word immutable here altogether. Though it would be nice if there was a solution where this whole thing is immutable... not sure what that'd look like though.

**Review by matthchr — APPROVED** [review]

File: v2/tools/generator/internal/codegen/pipeline/export_controller_type_registrations.go (hunk 1 above)
Comment (theunrepentantgeek) [reply v2/tools/generator/internal/codegen/pipeline/export_controller_type_registrations.go:259]: Done.

File: v2/tools/generator/internal/codegen/pipeline/export_controller_type_registrations.go (hunk 2 above)
Comment (theunrepentantgeek) [reply v2/tools/generator/internal/codegen/pipeline/export_controller_type_registrations.go:109]: Renamed to `chainsByName` as it's acting as an index where we can determine if two (or more) chains are sharing the same name.

File: v2/tools/generator/internal/codegen/pipeline/export_controller_type_registrations.go (hunk 4 above)
Comment (theunrepentantgeek) [reply v2/tools/generator/internal/codegen/pipeline/export_controller_type_registrations.go:196]: Rephrased, and took out the word _immutable_.
