### PR TITLE
Ensure resource names are always K8s compliant

### LINKED ISSUE #4153: Bug: asoctl import error:   a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters
**Version of Azure Service Operator**

azure_service_operator:v2.0.0-beta.2
asoctl: asoctl v2.8.0 linux

**Describe the bug**
When import an existing Azure postgresql flexible server,  we encountered the following error:

Error from server (Invalid): error when creating "aso.yaml": FlexibleServersConfiguration.dbforpostgresql.azure.com "testpgb01-archive_command" is invalid: metadata.name: Invalid value: "testpgb01-archive_command": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
Error from server (Invalid): error when creating "aso.yaml": FlexibleServersConfiguration.dbforpostgresql.azure.com "testpgb01-archive_mode" is invalid: metadata.name: Invalid value: "testpgb01-archive_mode": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
Error from server (Invalid): error when creating "aso.yaml": FlexibleServersConfiguration.dbforpostgresql.azure.com "testpgb01-authentication_timeout" is invalid: metadata.name: Invalid value: "testpgb01-authentication_timeout": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')

**To Reproduce**

1. manually create an Azure postgresql flexible server from portal.
2. use asoctl import the Azure postgresql flexible server to ASO.

**Expected behavior**

**Screenshots**
image

**Additional context**

### LINKED ISSUE #4156: Avoid assigning illegal names when importing resources
**Describe the current behavior**

When doing an import from Azure, `asoctl import azure-resource` currently assigns the name of the Azure resource as the name of the Kubernetes cluster - but as reported in #4153 not all legal Azure names are legal Kubernetes names.

**Describe the improvement**

Sanitize the names to ensure they're Kubernetes compliant, filling in AzureName where required to maintain the name used in Azure.

**Additional context**

Ownership references need to be updated too.

### PR DESCRIPTION
**Pull request by theunrepentantgeek**
**What this PR does / why we need it**:

Modifies resources names pulled from Azure to make them valid names for Kubernetes Resources.

Closes #4156 

Closes #4153 

**How does this PR make you feel**:
gif

**If applicable**:
- [x] this PR contains tests

### CODE REVIEW

File: v2/cmd/asoctl/internal/importing/importable_arm_resource.go [hunk 1]
```diff
@@ -556,6 +560,48 @@ func (i *importableARMResource) SetOwner(
...
+}
+
+var safeResourceNameRegex = regexp.MustCompile("-+")
+
+// safeResourceName ensures the name is a valid Kubernetes name
+func safeResourceName(name string) string {
+	buffer := make([]rune, 0, len(name))
+
+	for _, r := range name {
+		if unicode.IsLetter(r) || unicode.IsNumber(r) {
```
Comment (matthchr) [inline v2/cmd/asoctl/internal/importing/importable_arm_resource.go:577]: Would crafting this like this be clearer?
```
	for _, r := range name {
		if unicode.IsLetter(r) || unicode.IsNumber(r) {
			buffer = append(buffer, unicode.ToLower(r))
		} else if len(buffer) == 0 { 
			// Discard leading special characters so that the result always starts with a letter or number
			continue
		} else if c, ok := safeResourceNameMappings[r]; ok {
			buffer = append(buffer, c)
		} else if unicode.IsSpace(r) {
			buffer = append(buffer, '-')
		}
	}
```

For whatever reason it took me a second when reading this to realize "oh all of these cases are mutually exclusive"

**Review by matthchr — APPROVED** [review]

File: v2/cmd/asoctl/internal/importing/importable_arm_resource.go (hunk 1 above)
Comment (theunrepentantgeek) [reply v2/cmd/asoctl/internal/importing/importable_arm_resource.go:577]: I don't find a chain of **if**..**else** to be very readable; instead, I refactored it to use a **switch**, which I think is clearer than both what I had and what you suggested.
