### PR TITLE
Fix asoctl when importing resources with fixed names

### LINKED ISSUE #3098: Bug: asoctl panic during import
**Describe the bug**

Importing azure resources can crash with a panic:

```
panic: reflect: call of reflect.Value.SetString on zero Value

goroutine 3028 [running]:
reflect.flag.mustBeAssignableSlow(0x0?)
        /home/bevan/.gvm/gos/go1.20.4/src/reflect/value.go:255 +0x116
reflect.flag.mustBeAssignable(...)
        /home/bevan/.gvm/gos/go1.20.4/src/reflect/value.go:249
reflect.Value.SetString({0x0?, 0x0?, 0xc0007eb790?}, {0xc000514334, 0x7})
        /home/bevan/.gvm/gos/go1.20.4/src/reflect/value.go:2437 +0x4f
github.com/Azure/azure-service-operator/v2/cmd/asoctl/internal/importing.(*importableARMResource).SetName(0xc000b321cb?, {0x7f8f90bef480, 0xc00091e5a0}, {0xc000514334, 0x7}, {{0xc0007240c0, 0x11}, {0x4178c1e, 0xe}, {0xc000b72000, ...}, ...})
        /home/bevan/github/azure-service-operator/v2/cmd/asoctl/internal/importing/importable_arm_resource.go:484 +0x1ae
github.com/Azure/azure-service-operator/v2/cmd/asoctl/internal/importing.(*importableARMResource).createImportableObjectFromID(0xc00065a570, 0xc000ae8cc0, 0xc000b0c240)
        /home/bevan/github/azure-service-operator/v2/cmd/asoctl/internal/importing/importable_arm_resource.go:374 +0x23c
github.com/Azure/azure-service-operator/v2/cmd/asoctl/internal/importing.(*importableARMResource).importResource(0xc00065a570, {0x55a8ef8, 0xc00011e2d0}, 0xc000b0c240)
        /home/bevan/github/azure-service-operator/v2/cmd/asoctl/internal/importing/importable_arm_resource.go:140 +0x7c
github.com/Azure/azure-service-operator/v2/cmd/asoctl/internal/importing.(*importableARMResource).Import(0xc00065a570, {0x55a8ef8, 0xc00011e2d0}, 0x3?)
        /home/bevan/github/azure-service-operator/v2/cmd/asoctl/internal/importing/importable_arm_resource.go:94 +0x79
github.com/Azure/azure-service-operator/v2/cmd/asoctl/internal/importing.(*ResourceImporter).ImportResource(0xc0001d0150, {0x55a8ef8, 0xc00011e2d0}, {0x55a90b8?, 0xc00065a570?})
        /home/bevan/github/azure-service-operator/v2/cmd/asoctl/internal/importing/resource_importer.go:188 +0x54e
github.com/Azure/azure-service-operator/v2/cmd/asoctl/internal/importing.(*ResourceImporter).Import.func1()
        /home/bevan/github/azure-service-operator/v2/cmd/asoctl/internal/importing/resource_importer.go:136 +0x48
golang.org/x/sync/errgroup.(*Group).Go.func1()
        /home/bevan/.gvm/pkgsets/go1.20.4/global/pkg/mod/golang.org/x/sync@v0.1.0/errgroup/errgroup.go:75 +0x64
created by golang.org/x/sync/errgroup.(*Group).Go
        /home/bevan/.gvm/pkgsets/go1.20.4/global/pkg/mod/golang.org/x/sync@v0.1.0/errgroup/errgroup.go:72 +0xa5
```
**To Reproduce**

``` bash
asoctl import azure-resource <resource-group>
```

The crash occurs if the resource group being imported contains any resource that has a hardcoded name. For example, `Microsoft.Storage/storageAccounts/tableServices` must always be called `default` so we can't set the name.

**Expected behavior**

Import should work without crashing.

### PR DESCRIPTION
**Pull request by theunrepentantgeek**
**What this PR does / why we need it**:

If a resource being imported has a fixed name, it doesn't have an AzureName property and `asoctl` was encountering a panic.

Fixes #3098 

**How does this PR make you feel**:
gif

### CODE REVIEW

File: v2/cmd/asoctl/internal/importing/importable_arm_resource.go [hunk 1]
```diff
@@ -352,7 +352,7 @@ func (*importableARMResource) classifyError(err error) (string, bool) {
 func (i *importableARMResource) createImportableObjectFromID(
 	owner *genruntime.ResourceReference,
 	armID *arm.ResourceID,
-) (genruntime.ImportableARMResource, error) {
+) (resource genruntime.ImportableARMResource, failure error) {
```
Comment (matthchr) [inline v2/cmd/asoctl/internal/importing/importable_arm_resource.go:355]: minor: Would it make sense to use `err` here rather than failure?

File: v2/cmd/asoctl/internal/importing/resource_importer_report.go [hunk 2]
```diff
@@ -124,11 +125,28 @@ func (k *resourceImportReportKey) lessThan(other resourceImportReportKey) bool {
...
-		"Status", k.status,
-		"Count", count,
-		"Reason", k.reason)
+	switch k.status {
+	case Imported:
+		log.Info(
+			"Successful imports",
+			"Group", k.group,
+			"Kind", k.kind,
+
```
Comment (matthchr) [inline v2/cmd/asoctl/internal/importing/resource_importer_report.go:134]: minor: Excess newline?

**Review by matthchr — APPROVED** [review]

File: v2/cmd/asoctl/internal/importing/resource_importer_report.go (hunk 2 above)
Comment (theunrepentantgeek) [reply v2/cmd/asoctl/internal/importing/resource_importer_report.go:134]: Removed.

File: v2/cmd/asoctl/internal/importing/importable_arm_resource.go (hunk 1 above)
Comment (theunrepentantgeek) [reply v2/cmd/asoctl/internal/importing/importable_arm_resource.go]: I was avoiding a wider rewrite of the method - need to avoid shadowing of `err` with locals. I've done this now.
