### PR TITLE
Fix non-deterministic property comments 

### LINKED ISSUE #1757: Bug: Status types with properties overlapping with ResourceBase (name, type, etc) seem to have nondeterministic comments
I _think_ this only applies to Status types but I'm not 100% sure. An example was:
image

### PR DESCRIPTION
**Pull request by theunrepentantgeek**
**What this PR does / why we need it**:

When merging properties as a part of a one-of or all-of, the comment included on a merged property was non-deterministic, resulting in different results on different runs.

This PR applies a super simple heuristic, selecting the longer (more detailed) comment each time. This works pretty well, but isn't perfect.

Closes #1757 

**How does this PR make you feel**:
gif

### CODE REVIEW

File: hack/generator/pkg/codegen/pipeline/convert_allof_and_oneof_to_objects.go [hunk 1]
```diff
@@ -427,7 +430,15 @@ func (s synthesizer) handleObjectObject(leftObj *astmodel.ObjectType, rightObj *
 			}
 
 			// TODO: need to handle merging requiredness and tags and...
-			mergedProps[p.PropertyName()] = existingProp.WithType(newType)
+			newProp := existingProp.WithType(newType)
+			if len(p.Description()) > len(newProp.Description()) {
+				// When we merge properties, both of them may have comments, and we need to deterministically choose one
```
Comment (matthchr) [inline hack/generator/pkg/codegen/pipeline/convert_allof_and_oneof_to_objects.go:435]: TODO + link open issue here?

**Review by matthchr — APPROVED** [review]

File: hack/generator/pkg/codegen/pipeline/convert_allof_and_oneof_to_objects.go (hunk 1 above)
Comment (theunrepentantgeek) [reply hack/generator/pkg/codegen/pipeline/convert_allof_and_oneof_to_objects.go:435]: Done.

**Review by Porges — APPROVED** [review]
