### PR TITLE
Fix docs for StorageAutogrow

### LINKED ISSUE #1483: Bug: Description of property 'storageAutogrow' is wrong
**Describe the bug**
The description of property 'storageAutogrow' is wrong. 
https://github.com/Azure/azure-service-operator/blob/master/charts/azure-service-operator/crds/apiextensions.k8s.io_v1beta1_customresourcedefinition_mysqlservers.azure.microsoft.com.yaml#L216 
When I set the value to ''StorageAutogrowEnabled'' as the description suggested, the deploy failed with "Original Error: Code=\"InvalidStorageAutoGrow\" Message=\"Invalid Storage AutoGrow Value\" "

**Expected behavior**
It turns out the allowed values are "Enabled" and "Disabled". Please fix the property definition.

### PR DESCRIPTION
**Pull request by theunrepentantgeek**
**What this PR does / why we need it**:

Updates the documentation for `StorageAutogrow` to correctly show the available values as `Enabled` and `Disabled`.

Thanks @maggiexian for reporting the issue.

**How does this PR make you feel**:
[#puppies](https://media.giphy.com/media/MlIz6P8tUKAIeo1jgN/giphy.gif)

**If applicable**:
- [x] this PR contains documentation
- [ ] this PR contains tests

Closes #1483

### CODE REVIEW

**Review by babbageclunk — APPROVED** [review]

File: api/v1alpha2/sharedazuredbs_types.go [hunk 1]
```diff
@@ -77,7 +77,7 @@ type PSQLStorageProfile struct {
 	GeoRedundantBackup psql.GeoRedundantBackup `json:"geoRedundantBackup,omitempty"`
 	// StorageMB - Max storage allowed for a server.
 	StorageMB *int32 `json:"storageMB,omitempty"`
-	// StorageAutogrow - Enable Storage Auto Grow. Possible values include: 'StorageAutogrowEnabled', 'StorageAutogrowDisabled'
+	// StorageAutogrow - Enable Storage Auto Grow. Possible values include: 'Enabled', 'Disabled'
 	StorageAutogrow psql.StorageAutogrow `json:"storageAutogrow,omitempty"`
```
Comment (matthchr) [inline api/v1alpha2/sharedazuredbs_types.go:81]: If you also annotate this with:
`// +kubebuilder:validation:Enum=Enabled,Disabled`, it'll reject other values at YAM: submit time
