### PR TITLE
Mark Replica_Spec.Sku as required

### LINKED ISSUE #4672: Bug: SignalR Replica mandatory field is marked as optional
## Describe the bug

The SKU is mandatory for SignalR replicas:

https://github.com/Azure/azure-service-operator/blob/ba00156bcd685ee73f96bcf8ad3ca73d3e5e329d/v2/api/signalrservice/v1api20240301/replica_types_gen.go#L280-L281

Azure Service Operator Version: v2.12.0

## Expected behavior

Replica objects should not be accepted by the API server if they are invalid

```
Unhandled Exception in Azure SignalR service. Please try again later.: PUT https://management.azure.com/subscriptions/000000000000000/resourceGroups/local-we-rg/providers/Microsoft.SignalRService/signalR/local-we-signalr/replicas/local-we-signalr-we 
 -replica                                                                                                                                                                                                                                                                             
       --------------------------------------------------------------------------------                                                                                                                                                                                               
       RESPONSE 500: 500 Internal Server Error                                                                                                                                                                                                                                        
       ERROR CODE: InternalServerError                                                                                                                                                                                                                                                
       --------------------------------------------------------------------------------                                                                                                                                                                                               
       {                                                                                                                                                                                                                                                                              
         "error": {                                                                                                                                                                                                                                                                   
           "code": "InternalServerError",                                                                                                                                                                                                                                             
           "message": "Unhandled Exception in Azure SignalR service. Please try again later."                                                                                                                                                                                         
         }                                                                                                                                                                                                                                                                            
       }                                                                                                                                                                                                                                                                              
       -------------------------------------------------------------------------------- 
```

## To Reproduce

```
apiVersion: signalrservice.azure.com/v1api20240301
kind: Replica
metadata:
  name: local-we-signalr-we-replica
  namespace: local
spec:
  azureName: local-we-signalr-we-replica
  location: westeurope
  owner:
    name: local-we-signalr
#  sku:
#    name: Premium_P1
---
apiVersion: signalrservice.azure.com/v1api20211001
kind: SignalR
metadata:
  name: local-we-signalr
  namespace: local
spec:
  azureName: local-we-signalr
  features:
  - flag: EnableConnectivityLogs
    value: "true"
  identity:
    type: SystemAssigned
  location: westus2
  owner:
    name: local-we-rg
  sku:
    capacity: 1
    name: Premium_P1
    tier: Premium
```

### PR DESCRIPTION
**Pull request by theunrepentantgeek**
## What this PR does

Marks the `sku` property of `signalrservice/ReplicaSpec` as mandatory.

Closes #4672 

## How does this PR make you feel?

gif

### CODE REVIEW

File: v2/tools/generator/internal/config/type_transformer.go [hunk 1]
```diff
@@ -316,6 +316,12 @@ func (transformer *TypeTransformer) transformProperties(
 				return nil, eris.Wrapf(err, "transforming property %s", propertyName)
 			}
 
+			if transformer.Target.Optional {
```
Comment (matthchr) [inline v2/tools/generator/internal/config/type_transformer.go:319]: Should we error if somebody sets both option and required to true?

**Review by matthchr — DISMISSED** [review]

File: v2/tools/generator/internal/config/type_transformer.go (hunk 1 above)
Comment (theunrepentantgeek) [reply v2/tools/generator/internal/config/type_transformer.go:324]: Good idea. Done.

**Comment by theunrepentantgeek** [comment]
We've had confirmation from the product group that `sku` is mandatory for creation of a replica, but not for updates. For ASO, it makes sense to make the property mandatory. They'll be releasing an update shortly to return a validation error instead of a server error if it's missing.

**Review by matthchr — APPROVED** [review]
