### PR TITLE
Modify Enum conversions to be case-insensitive/case-correcting

### LINKED ISSUE #3805: Bug: `asoctl import`-ing a ManagedCluster produces an invalid resource
**Version of Azure Service Operator**

v2.5.0

**Describe the bug**
`asoctl import`-ing an AKS cluster created with `az aks create` with only the required parameters produces invalid values that trigger validation errors from the AKS API.

I had to make the following tweaks to the generated YAML to get the ManagedCluster to reconcile successfully:

`spec.networkProfile.loadBalancerProfile.backendPoolType`: nodeIPConfiguration -> NodeIPConfiguration

`spec.networkProfile.loadBalancerSku`: Standard -> standard

**To Reproduce**

```
az group create -n adopt-test -l eastus && az aks create -g adopt-test -n adopt1
asoctl import azure-resource /subscriptions/<sub>/resourceGroups/adopt-test -o managedcluster.yaml
# Delete all but the ResourceGroup and ManagedCluster resources, then
kubectl apply -f managedcluster.yaml
```

**Expected behavior**
`asoctl import` produces valid YAML that doesn't require any additional changes to reconcile successfully.

**Screenshots**

**Additional context**

### PR DESCRIPTION
**Pull request by theunrepentantgeek**
**What this PR does / why we need it**:

In some cases information returned about a resource is is inconsistent with the letter casing specified in the OpenAPI specs for a resource - for example, the specs might specify `Succeeded` but the service returns `succeeded`.

This PR modifies enum conversion to work in a case-insensitive way, which will case-correct values to conform with the OpenAPI specs.

**Special notes for your reviewer**:

The conversion from `status` to `spec` used by **asoctl** will also pick up this fix.

Closes #3805 

**How does this PR make you feel**:
gif

### CODE REVIEW

File: v2/tools/generator/internal/astbuilder/builder.go [hunk 1]
```diff
@@ -477,6 +477,10 @@ func Statements(statements ...any) []dst.Stmt {
 		case []dst.Stmt:
 			// Add many statements
 			stmts = append(stmts, s...)
+		case dst.Decl:
+			// Convert declaration to statement
+			stmt := &dst.DeclStmt{Decl: s}
+			stmts = append(stmts, stmt)
 		default:
 			panic(fmt.Sprintf("expected dst.Stmt or []dst.Stmt, but found %T", s))
```
Comment (matthchr) [inline v2/tools/generator/internal/astbuilder/builder.go:485]: Fix this error message too?

File: v2/tools/generator/internal/astbuilder/declarations.go [hunk 2]
```diff
@@ -0,0 +1,38 @@
...
+
+package astbuilder
+
+import (
+	"fmt"
+
+	"github.com/dave/dst"
+)
+
+func Declarations(declarations ...any) []dst.Decl {
```
Comment (matthchr) [inline v2/tools/generator/internal/astbuilder/declarations.go:14]: Duplicate from your other PR?

File: v2/tools/generator/internal/astmodel/enum_type.go [hunk 3]
```diff
@@ -40,9 +41,28 @@ func NewEnumType(baseType *PrimitiveType, options ...EnumValue) *EnumType {
...
 
-	sort.Slice(options, func(left int, right int) bool {
-		return options[left].Identifier < options[right].Identifier
-	})
+	slices.SortFunc(
+		options,
+		func(left EnumValue, right EnumValue) int {
+			if baseType == IntType {
+				// Compare integers as numbers if we can
+				l, lOk := strconv.Atoi(left.Identifier)
```
Comment (matthchr) [inline v2/tools/generator/internal/astmodel/enum_type.go:49]: Is this also duplicate from your other PR?

Comment (matthchr) [reply v2/tools/generator/internal/astmodel/enum_type.go:49]: Hmm maybe not?

File: v2/api/apimanagement/v1api20220801/api_version_set_types_gen.go [hunk 4]
```diff
@@ -955,6 +966,13 @@ const (
 	ApiVersionSetContractProperties_VersioningScheme_Segment = ApiVersionSetContractProperties_VersioningScheme("Segment")
 )
 
+// Mapping from string to ApiVersionSetContractProperties_VersioningScheme
+var ApiVersionSetContractProperties_VersioningScheme_Cache = map[string]ApiVersionSetContractProperties_VersioningScheme{
```
[the remark this answers is not in the document]
Comment (theunrepentantgeek) [reply v2/api/apimanagement/v1api20220801/api_version_set_types_gen.go:970]: Yeah, values might be better.

[the remark this answers is not in the document]
Comment (theunrepentantgeek) [reply v2/api/apimanagement/v1api20220801/api_version_set_types_gen.go:970]: Agreed. There's a small challenge in not having a readily available `IdentiferFactory`, but I can fake up something local.

File: v2/api/apimanagement/v1api20220801/api_version_set_types_gen.go [hunk 5]
```diff
@@ -569,8 +570,13 @@ func (versionSet *Service_ApiVersionSet_Spec) AssignProperties_From_Service_ApiV
 
 	// VersioningScheme
 	if source.VersioningScheme != nil {
-		versioningScheme := ApiVersionSetContractProperties_VersioningScheme(*source.VersioningScheme)
-		versionSet.VersioningScheme = &versioningScheme
+		versioningScheme := *source.VersioningScheme
```
Comment (matthchr) [inline v2/api/apimanagement/v1api20220801/api_version_set_types_gen.go:573]: I wrote this once before but GitHub ate it:

Consider instead of doing this in every generated method, creating a helper:
```
func CaseCorrectEnum[T ~string](val string, map[string]T) T
```

and then just call that in the generated code:
```
CaseCorrectEnum(versioningScheme, ApiVersionSetContractProperties_VersioningScheme_Cache)
```

File: v2/api/apimanagement/v1api20230501preview/storage/api_types_gen.go [hunk 6]
```diff
@@ -231,6 +231,11 @@ type APIVersion string
 
 const APIVersion_Value = APIVersion("2023-05-01-preview")
 
+// Mapping from string to APIVersion
+var APIVersion_Cache = map[string]APIVersion{
```
[the remark this answers is not in the document]
Comment (theunrepentantgeek) [reply v2/api/apimanagement/v1api20230501preview/storage/api_types_gen.go:235]: Yeah, that makes sense.

File: v2/tools/generator/internal/astbuilder/assert.go [hunk 7]
```diff
@@ -0,0 +1,81 @@
...
+
+	. "github.com/onsi/gomega"
+
+	"github.com/dave/dst"
+	"github.com/dave/dst/decorator"
+	"github.com/sebdah/goldie/v2"
+)
+
+// AssertExprExpected asserts the given expression generates the expected code, comparing it to a golden file
+func AssertExprExpected(t *testing.T, expr dst.Expr) {
```
[the remark this answers is not in the document]
Comment (theunrepentantgeek) [reply v2/tools/generator/internal/astbuilder/assert.go:20]: I think all I need to do is rename the file to `assert_test.go`.

File: v2/tools/generator/internal/astbuilder/declarations.go (hunk 2 above)
Comment (theunrepentantgeek) [reply v2/tools/generator/internal/astbuilder/declarations.go:14]: I pulled it out of here for that PR, knowing I'd need to rebase this one.

File: v2/tools/generator/internal/astmodel/enum_type.go (hunk 3 above)
Comment (theunrepentantgeek) [reply v2/tools/generator/internal/astmodel/enum_type.go:49]: I pulled it out of here for a different PR, knowing I'd need to rebase this one.

File: v2/api/apimanagement/v1api20220801/api_version_set_types_gen.go (hunk 5 above)
Comment (theunrepentantgeek) [reply v2/api/apimanagement/v1api20220801/api_version_set_types_gen.go:573]: Good idea.

Comment (matthchr) [reply v2/api/apimanagement/v1api20220801/api_version_set_types_gen.go:573]: https://go.dev/play/p/4QlmlZearvY?v=goprev

File: v2/tools/generator/internal/astbuilder/assert.go (hunk 7 above)
[the remark this answers is not in the document]
Comment (matthchr) [reply v2/tools/generator/internal/astbuilder/assert.go]: Oh yes, I missed that they aren't ever used outside the package.

File: v2/api/apimanagement/v1api20220801/api_version_set_types_gen.go (hunk 4 above)
[the remark this answers is not in the document]
Comment (theunrepentantgeek) [reply v2/api/apimanagement/v1api20220801/api_version_set_types_gen.go]: Done.

[the remark this answers is not in the document]
Comment (theunrepentantgeek) [reply v2/api/apimanagement/v1api20220801/api_version_set_types_gen.go]: Done.

File: v2/api/apimanagement/v1api20230501preview/storage/api_types_gen.go (hunk 6 above)
[the remark this answers is not in the document]
Comment (theunrepentantgeek) [reply v2/api/apimanagement/v1api20230501preview/storage/api_types_gen.go]: I've excluded `APIVersion` specifically.

File: v2/tools/generator/internal/astbuilder/assert.go (hunk 7 above)
[the remark this answers is not in the document]
Comment (theunrepentantgeek) [reply v2/tools/generator/internal/astbuilder/assert.go]: Done.

File: v2/tools/generator/internal/astbuilder/builder.go (hunk 1 above)
Comment (theunrepentantgeek) [reply v2/tools/generator/internal/astbuilder/builder.go]: Fixed.

File: v2/api/apimanagement/v1api20220801/api_version_set_types_gen.go (hunk 5 above)
Comment (theunrepentantgeek) [reply v2/api/apimanagement/v1api20220801/api_version_set_types_gen.go:572]: Done.

File: v2/pkg/genruntime/enum.go [hunk 8]
```diff
@@ -0,0 +1,18 @@
...
+ * Licensed under the MIT license.
+ */
+
+package genruntime
+
+import "strings"
+
+// ToEnum does a case-insensitive conversion of a string to an enum using a provided conversion map.
+// If the required value is not found, a literal cast will be used to return the enum.
+func ToEnum[T ~string](str string, enumMap map[string]T) T {
```
Comment (matthchr) [inline v2/pkg/genruntime/enum.go:12]: Very cool

File: v2/tools/generator/internal/codegen/testdata/ArmResource/Arm_test_required_and_optional_resource_references_azure.golden [hunk 9]
```diff
@@ -298,6 +298,11 @@ type FakeResource_APIVersion_Spec string
 
 const FakeResource_APIVersion_Spec_20200601 = FakeResource_APIVersion_Spec("2020-06-01")
 
+// Mapping from string to FakeResource_APIVersion_Spec
+var fakeResource_APIVersion_Spec_Values = map[string]FakeResource_APIVersion_Spec{
```
Comment (matthchr) [inline v2/tools/generator/internal/codegen/testdata/ArmResource/Arm_test_required_and_optional_resource_references_azure.golden:302]: Any idea why this apiversion in the test isn't getting excluded?

**Review by matthchr — APPROVED** [review]

File: v2/tools/generator/internal/codegen/testdata/ArmResource/Arm_test_required_and_optional_resource_references_azure.golden (hunk 9 above)
Comment (theunrepentantgeek) [reply v2/tools/generator/internal/codegen/testdata/ArmResource/Arm_test_required_and_optional_resource_references_azure.golden:302]: Because the type isn't called exactly `APIVersion` - I'm guessing because the name isn't being simplified in the same way as the main pipeline.

File: v2/pkg/genruntime/enum.go (hunk 8 above)
Comment (theunrepentantgeek) [reply v2/pkg/genruntime/enum.go:12]: Yeah. Full credit though - you gave me the method signature. :grin:
