### PR TITLE
[Bug fix] Azure SQL Managed Identity can get stuck in deleting when the database the user is in is deleted

### LINKED ISSUE #1254: Bug: When deleting AzureSQLDatabase and AzureSQLManagedUser at the same time, sometimes the managed user can get stuck
**Describe the bug**
When deleting AzureSQLDatabase and AzureSQLManagedUser at the same time, sometimes the managed user can get stuck.

**To Reproduce**
1. Create an Azure SQL DB and managed user, and delete both at the same time, or delete the DB first, wait for it to be in deleting state/deleted, and then delete the managed user.
2. Observe that sometimes the managed user gets stuck.

**Expected behavior**
Both are deleted

**Additional context**
Can see this as the state of the user:
```
k get azuresqlmanagedusers -n klt6-private-predev
NAME      PROVISIONED   MESSAGE
sqluser   true          PingContext failed: Login error: mssql: Login failed for user '<token-identified principal>'.
```

### PR DESCRIPTION
**Pull request by matthchr**
Closes #1254

**What this PR does / why we need it**: A few makefile cleanups and fixing a bug causing resource to get stuck in deleting state.

**Special notes for your reviewer**:
We currently cannot write an automated test for this scenario because the SqlManagedIdentity user only works in a real AKS cluster on Azure (due to how ManagedIdentity works). I tested it manually before sending the PR.

**If applicable**:
- [ ] this PR contains documentation
- [ ] this PR contains tests

### CODE REVIEW

File: pkg/resourcemanager/azuresql/azuresqlmanageduser/azuresqlmanageduser_reconcile.go [hunk 1]
```diff
@@ -146,7 +146,24 @@ func (s *AzureSqlManagedUserManager) Delete(ctx context.Context, obj runtime.Obj
 		requestedUsername = instance.Name
 	}
 
-	db, err := s.ConnectToSqlDbAsCurrentUser(ctx, DriverName, instance.Spec.Server, instance.Spec.DbName)
+	// short circuit connection if database doesn't exist
+	_, err = s.GetDB(ctx, instance.Spec.ResourceGroup, instance.Spec.Server, instance.Spec.DbName)
```
Comment (babbageclunk) [inline pkg/resourcemanager/azuresql/azuresqlmanageduser/azuresqlmanageduser_reconcile.go:150]: Was the underlying problem that the connect call would hang if the database doesn't exist? Should we also add a timeout on the connect? It seems like there could be other problems where the DB exists but connect still hangs - presumably that would block reconciliation.

**Review by babbageclunk — APPROVED** [review]
Looks good, but maybe a timeout would be worthwhile too.

File: Makefile [hunk 2]
```diff
@@ -212,26 +212,30 @@ install-bindata:
...
+kind-create: install-kind
+	kind get clusters | grep -E $(KIND_CLUSTER_NAME) > /dev/null;\
+	EXISTS=$$?;\
+	if [ $$EXISTS -eq 0 ]; then \
+		echo "$(KIND_CLUSTER_NAME) already exists"; \
+	else \
+		kind create cluster --name=$(KIND_CLUSTER_NAME); \
+	fi; \
+
+set-kindcluster: install-kind kind-create
```
Comment (Porges) [inline Makefile:231]: This should be phony too?

Comment (matthchr) [reply Makefile:231]: Yes

File: pkg/resourcemanager/azuresql/azuresqlmanageduser/azuresqlmanageduser_reconcile.go (hunk 1 above)
Comment (matthchr) [reply pkg/resourcemanager/azuresql/azuresqlmanageduser/azuresqlmanageduser_reconcile.go:150]: Doesn't hang - errored with connection rejected.

**Review by Porges — APPROVED** [review]

File: pkg/resourcemanager/azuresql/azuresqlmanageduser/azuresqlmanageduser_reconcile.go (hunk 1 above)
Comment (babbageclunk) [reply pkg/resourcemanager/azuresql/azuresqlmanageduser/azuresqlmanageduser_reconcile.go:150]: Oh ok.

File: pkg/resourcemanager/azuresql/azuresqlmanageduser/azuresqlmanageduser_reconcile.go [hunk 3]
```diff
@@ -146,7 +146,24 @@ func (s *AzureSqlManagedUserManager) Delete(ctx context.Context, obj runtime.Obj
...
+		catch := []string{
+			errhelp.ResourceNotFound,
+			errhelp.ParentNotFoundErrorCode,
+			errhelp.ResourceGroupNotFoundErrorCode,
+		}
+		azerr := errhelp.NewAzureErrorAzureError(err)
+		if helpers.ContainsString(catch, azerr.Type) {
+			return false, nil
+		}
+		return false, err
```
Comment (babbageclunk) [inline pkg/resourcemanager/azuresql/azuresqlmanageduser/azuresqlmanageduser_reconcile.go:163]: Sorry I missed this first time around, but since this case is a delete success (because the DB's gone) I think you need to do the secret deletion for it as well.

Comment (matthchr) [reply pkg/resourcemanager/azuresql/azuresqlmanageduser/azuresqlmanageduser_reconcile.go:163]: Woaah, I totally missed that. Good catch.

File: pkg/resourcemanager/azuresql/azuresqlmanageduser/azuresqlmanageduser_reconcile.go (hunk 1 above)
Comment (matthchr) [reply pkg/resourcemanager/azuresql/azuresqlmanageduser/azuresqlmanageduser_reconcile.go:150]: It looks like the AutoRest clients already have timeouts configured:
```
	transport := &http.Transport{
		Proxy:                 defaultTransport.Proxy,
		DialContext:           defaultTransport.DialContext,
		MaxIdleConns:          defaultTransport.MaxIdleConns,
		IdleConnTimeout:       defaultTransport.IdleConnTimeout,
		TLSHandshakeTimeout:   defaultTransport.TLSHandshakeTimeout,
		ExpectContinueTimeout: defaultTransport.ExpectContinueTimeout,
		TLSClientConfig: &tls.Config{
			MinVersion:    tls.VersionTLS12,
			Renegotiation: renengotiation,
		},
	}
```

Values seem to be this:
```
	Proxy: ProxyFromEnvironment,
	DialContext: (&net.Dialer{
		Timeout:   30 * time.Second,
		KeepAlive: 30 * time.Second,
		DualStack: true,
	}).DialContext,
	ForceAttemptHTTP2:     true,
	MaxIdleConns:          100,
	IdleConnTimeout:       90 * time.Second,
	TLSHandshakeTimeout:   10 * time.Second,
	ExpectContinueTimeout: 1 * time.Second,
```

So I think we're good there.

**Review by babbageclunk — APPROVED** [review]
Looks great!
