### PR TITLE
Fix BackupVaults/BackupInstance extension to exit early on terminal states

### LINKED ISSUE #4135: PostReconcileCheck not running on BackupVaultBackupInstance resource
**Version**

ASO v2.7.0 
 

**Describe the bug**
Seeing a regressed behavior where there is no post reconciliation and BeginSyncBackupInstance called on the BackupVaultsBackupInstance even though it was failed user error and in protection error state (our condition in post reconciliation)

https://github.com/mayankagg9722/azure-service-operator/blob/e66c3fd05fc6af0a4efb0551b858d01eee2c7376/v2/api/dataprotection/customizations/backup_vaults_backup_instance_extensions.go#L98 

**To Reproduce**
Post performing all the prerequisutes, create the BackupVaultBackupInstance resource in the cluster using ASO.
Use this Yaml: 
[bie2etest.txt](https://github.com/user-attachments/files/15971687/bie2etest.txt)

**Expected behavior**
BeginSyncBackupInstance should be called which is there in the reconciliation flow.

https://github.com/mayankagg9722/azure-service-operator/blob/e66c3fd05fc6af0a4efb0551b858d01eee2c7376/v2/api/dataprotection/customizations/backup_vaults_backup_instance_extensions.go#L98 

**Screenshots**
Activity logs portal:

image

Backup Instance:

image
image

ASO Logs:
image

[asologs.txt](https://github.com/user-attachments/files/15971653/asologs.txt)
[asologs1.txt](https://github.com/user-attachments/files/15971655/asologs1.txt)

Backup Instance YAML in Cluster:

image

### PR DESCRIPTION
**Pull request by super-harsh**
Closes #4135 

**What this PR does / why we need it**:

Fix BackupVaults/BackupInstance extension to exit early on terminal states. Most of the changes are reverted from [commit](https://github.com/Azure/azure-service-operator/pull/3953/files) which introduced the bug.

### CODE REVIEW

File: v2/api/dataprotection/customizations/backup_vaults_backup_instance_extensions.go [hunk 1]
```diff
@@ -19,14 +19,26 @@ import (
...
+	"github.com/Azure/azure-service-operator/v2/internal/set"
 	"github.com/Azure/azure-service-operator/v2/internal/util/to"
 	"github.com/Azure/azure-service-operator/v2/pkg/genruntime"
 	"github.com/Azure/azure-service-operator/v2/pkg/genruntime/extensions"
 )
 
 var _ extensions.PostReconciliationChecker = &BackupVaultsBackupInstanceExtension{}
 
-var protectionError = "ProtectionError"
+var terminalStates = set.Make(
```
Comment (matthchr) [inline v2/api/dataprotection/customizations/backup_vaults_backup_instance_extensions.go:30]: Can you add some documentation about how we determined this list, and what exactly it means to be terminal here?

File: v2/api/dataprotection/customizations/backup_vaults_backup_instance_extensions.go [hunk 2]
```diff
@@ -80,69 +92,73 @@ func (extension *BackupVaultsBackupInstanceExtension) PostReconcileCheck(
...
 
 	protectionStatus := *backupInstance.Status.Properties.ProtectionStatus.Status
+	protectionStatus = strings.ToLower(protectionStatus)
 	log.V(Debug).Info(fmt.Sprintf("Protection Status is  %q", protectionStatus))
 
-	// We only want to continue if protectionStatus == ProtectionError.
-	if !strings.EqualFold(protectionStatus, protectionError) {
+	// Return success if the status is in a terminal state
+	if terminalStates.Contains(protectionStatus) {
 		log.V(Debug).Info("Returning PostReconcileCheckResultSuccess")
```
Comment (matthchr) [inline v2/api/dataprotection/customizations/backup_vaults_backup_instance_extensions.go:100]: So we continue even if `configuringprotectionfailed`?

File: v2/api/dataprotection/customizations/backup_vaults_backup_instance_extensions.go [hunk 3]
```diff
@@ -80,69 +92,73 @@ func (extension *BackupVaultsBackupInstanceExtension) PostReconcileCheck(
...
+		var protectionStatusErrorCode string
+		protectionStatusErrorCode = strings.ToLower(*backupInstance.Status.Properties.ProtectionStatus.ErrorDetails.Code)
+		log.V(Debug).Info(fmt.Sprintf("Protection Error code is  %q", protectionStatusErrorCode))
 
-	if protectionStatusErrorCode != "" && strings.Contains(protectionStatusErrorCode, "usererror") {
-		id, _ := genruntime.GetAndParseResourceID(backupInstance)
-		subscription := id.SubscriptionID
-		rg := id.ResourceGroupName
-		vaultName := id.Parent.Name
+		if protectionStatusErrorCode != "" && strings.Contains(protectionStatusErrorCode, "usererror") {
```
Comment (matthchr) [inline v2/api/dataprotection/customizations/backup_vaults_backup_instance_extensions.go:110]: Is the `protectionStatusErrorCode != ""` really needed here?

**Review by matthchr — COMMENTED** [review]
Is there a test that could cover this case/issue?

File: v2/api/dataprotection/customizations/backup_vaults_backup_instance_extensions.go (hunk 2 above)
Comment (super-harsh) [reply v2/api/dataprotection/customizations/backup_vaults_backup_instance_extensions.go:102]: Yep. since its a failure, we'd let operator handle this case + set the condition and return success.

File: v2/api/dataprotection/customizations/backup_vaults_backup_instance_extensions.go (hunk 3 above)
Comment (super-harsh) [reply v2/api/dataprotection/customizations/backup_vaults_backup_instance_extensions.go]: Not really, removed it!

File: v2/api/dataprotection/customizations/backup_vaults_backup_instance_extensions.go (hunk 1 above)
Comment (mayankagg9722) [reply v2/api/dataprotection/customizations/backup_vaults_backup_instance_extensions.go:32]: These are the states listed and we do no foresee any frequent changed here as these states are not usually changed.
 
Swagger: https://github.com/Azure/azure-rest-api-specs/blob/a651ba25cda4eec698a3a4e35f867ecc2681d126/specification/dataprotection/resource-manager/Microsoft.DataProtection/stable/2023-11-01/dataprotection.json#L5014

Public Doc: (might not be updated with latest swagger)
https://learn.microsoft.com/en-us/rest/api/dataprotection/backup-instances/get?view=rest-dataprotection-2024-04-01&tabs=HTTP#status

File: v2/internal/controllers/crd_dataprotection_backupinstance_20231101_test.go [hunk 4]
```diff
@@ -32,7 +32,7 @@ func Test_DataProtection_BackupInstance_20231101_CRUD(t *testing.T) {
 	// Create a test resource group and wait until the operation is completed, where the globalTestContext is a global object that provides the necessary context and utilities for testing.
 	tc := globalTestContext.ForTest(t)
 	rg := tc.CreateTestResourceGroupAndWait()
-	contributorRoleId := fmt.Sprintf("/subscriptions/%s/providers/Microsoft.Authorization/roleDefinitions/17d1049b-9a84-46fb-8f53-869881c3d3ab", tc.AzureSubscription)
+	contributorRoleId := fmt.Sprintf("/subscriptions/%s/providers/Microsoft.Authorization/roleDefinitions/b24988ac-6180-42a0-ab88-20f7382dd24c", tc.AzureSubscription)
```
Comment (matthchr) [inline v2/internal/controllers/crd_dataprotection_backupinstance_20231101_test.go:35]: How did the contributor role change...? It's always the same GUID isn't it?

Is this new GUID a different role?

File: v2/api/dataprotection/customizations/backup_vaults_backup_instance_extensions.go (hunk 2 above)
Comment (matthchr) [reply v2/api/dataprotection/customizations/backup_vaults_backup_instance_extensions.go:102]: Ok fair enough - it's basically a fatal error.

File: v2/internal/controllers/crd_dataprotection_backupinstance_20231101_test.go (hunk 4 above)
Comment (super-harsh) [reply v2/internal/controllers/crd_dataprotection_backupinstance_20231101_test.go:35]: `17d1049b-9a84-46fb-8f53-869881c3d3ab` is storageAccountContributor and this one requires just `Contributor` to ResourceGroup. 

Not sure if it was incorrect or RP changed something but this one works now.

File: v2/api/dataprotection/customizations/backup_vaults_backup_instance_extensions.go (hunk 1 above)
Comment (theunrepentantgeek) [reply v2/api/dataprotection/customizations/backup_vaults_backup_instance_extensions.go:32]: Adding these URLs as comments would be useful, so that a future maintainer can go verify if things change in the future.

**Review by theunrepentantgeek — APPROVED** [review]

**Review by matthchr — APPROVED** [review]

File: v2/api/dataprotection/customizations/backup_vaults_backup_instance_extensions.go (hunk 1 above)
Comment (super-harsh) [reply v2/api/dataprotection/customizations/backup_vaults_backup_instance_extensions.go:34]: Done!
