### PR TITLE
Fix bug where some ConfigMap and Secret references could be missed

### LINKED ISSUE #4298: Data encryption - PostgreSQL Flexible Server
We have a policy / compliance requirement to use customer managed keys. I see that the PostgreSQL Flexible Server resource supports geoBackupKeyUri and primaryKeyUri which is great, but I don't see a way to generate those CMKs with ASOPv2. In terraform, we created one via `azurerm_key_vault_key` and gave the user-assigned managed identity access to it and nabbed the key URL from that. How can we achieve this with ASOP v2?

### LINKED ISSUE #4316: Bug: ConfigMap and Secret discovery doesn't work for properties that only exist on preview verisons
**Version of Azure Service Operator**
2.9.0

**Describe the bug**
When a `ConfigMapReference` field is exported _only_ in a preview version and not in the latest stable, the discovery mechanism we use to find the `ConfigMapReference` and look it up fails because it does the lookup on the storage version of the resource. The storage version of the resource has the `genruntime.ConfigMapReference` _in the PropertyBag_ of the storage version - but this means it's serialized to a string and isn't discoverable by reflection.

**To Reproduce**
Can be reproduced with PostgreSQLFlexibleServer GeoBackupKeyURI, see #4298

**Expected behavior**
ConfigMap export should work.

### PR DESCRIPTION
**Pull request by matthchr**
The ASO controller uses reflection to look through the resource and find the ConfigMapReference and SecretReference fields. This reflection could miss SecretReference and ConfigMapReference fields that had been serialized into the "PropertyBag" property on the storage type. This was most common when working with preview APIs that had added new ConfigMapReference or SecretReference fields that don't exist in the GA api version.

The fix is to use the converted version for reflection-based discovery.

Fixes #4298.
Fixes #4316.

**If applicable**:
- [ ] this PR contains documentation
- [x] this PR contains tests
- [ ] this PR contains YAML Samples

### CODE REVIEW

File: v2/pkg/genruntime/convertible.go [hunk 1]
```diff
@@ -0,0 +1,105 @@
...
+	interfaceType := reflect.TypeOf((*conversion.Hub)(nil)).Elem()
+
+	for gvk, rt := range scheme.AllKnownTypes() {
+		if gvk.Group != gk.Group || gvk.Kind != gk.Kind {
+			continue
+		}
+
+		if reflect.PointerTo(rt).Implements(interfaceType) {
+			return gvk, nil
+		}
```
Comment (theunrepentantgeek) [inline v2/pkg/genruntime/convertible.go:27]: Why not use the existing `NewEmptyVersionedResourceFromGVK()` and then test using `if _, ok := empty.(conversion.Hub); ok`, avoiding the cryptic reflection code?

**Review by super-harsh — APPROVED** [review]

File: v2/pkg/genruntime/convertible.go (hunk 1 above)
Comment (matthchr) [reply v2/pkg/genruntime/convertible.go:27]: Two reasons:
1. `scheme.AllKnownTypes` returns a `map[schema.GroupVersionKind]reflect.Type`, so it seemed to make some sense to stay in the "reflect world" when scanning it if I don't actually need an instance.
2. Since this is called in the (somewhat) hot path of the core reconcile loop logic, and can be hit at least a couple times through each loop (because there may be multiple versions of a resource for a given group + version) I was a bit concerned about performance/extra allocations. It _probably_ wouldn't matter but avoiding constructing 8-10 objects that are immediately thrown away when instead we can do a check via reflection that avoids those allocations.

I _almost_ just computed a map of this upfront once and then we could look it up whenever we wanted but that seemed overkill so instead settled on using a less-allocations approach using this reflection method that kept things "simple" (no extra variables to storage cached data that needed to be passed around) while still avoiding excess allocations.
