### PR TITLE
Retry on DNS Zone targetResource lookup not found

### LINKED ISSUE #4645: Bug: DnsZonesCNAMERecord resource doesn't resynced if "BadRequest"
## Describe the bug

When i'm trying to create at the same time TrafficManagerProfile and DnsZonesCNAMERecord pointed on it.
TrafficManagerProfile is created, but DnsZonesCNAMERecord is failed with BadRequest error

`Reason: BadRequest, Severity: Error, RetryClassification: RetrySlow, Cause: The referenced resource '/subscriptions/xxxx/resourceGroups/xxx/providers/Microsoft.Network/trafficManagerProfiles/test' was not found: PUT https://management.azure.com/subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.Network/dnszones/test.com/CNAME/test-azure -------------------------------------------------------------------------------- RESPONSE 400: 400 Bad Request ERROR CODE: BadRequest -------------------------------------------------------------------------------- { "code": "BadRequest", "message": "The referenced resource '\/subscriptions\/xxx\/resourceGroups\/xxx\/providers\/Microsoft.Network\/trafficManagerProfiles\/test' was not found" } ------------------`

DnsZonesCNAMERecord isn't synced even when TrafficManagerProfile is created.

Azure Service Operator Version: v2.12.0

## Expected behavior

DnsZonesCNAMERecord resource must be re-synced when TrafficManagerProfile is created

## To Reproduce

```
apiVersion: network.azure.com/v1api20220401storage
kind: TrafficManagerProfile
metadata:
  name: test
   namespace: test
spec:
  azureName: test
  dnsConfig:
    relativeName: test
    ttl: 30
  location: global
  monitorConfig:
    port: 80
    protocol: TCP
  originalVersion: v1api20220401
  owner:
    armId: >-
      /subscriptions/xxx/resourceGroups/xxx
  trafficRoutingMethod: Performance
```

```
apiVersion: network.azure.com/v1api20180501storage
kind: DnsZonesCNAMERecord
metadata:
  name: test
  namespace: test
spec:
  TTL: 30
  azureName: test
  originalVersion: v1api20180501
  owner:
    armId: >-
      /subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.Network/dnszones/test.com
  targetResource:
    reference:
      armId: >-
        /subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.Network/trafficManagerProfiles/test
```

## Additional context
slack thread link
https://kubernetes.slack.com/archives/C046DEVLAQM/p1742824034775289

### PR DESCRIPTION
**Pull request by matthchr**
This error is likely transient and can be retried on.

Closes #4645 

- [ ] this PR contains documentation
- [x] this PR contains tests
- [ ] this PR contains YAML Samples

### CODE REVIEW

File: v2/api/network/customizations/dns_zones_a_record_extension.go [hunk 1]
```diff
@@ -0,0 +1,34 @@
...
+	if err != nil {
+		return core.CloudErrorDetails{}, err
+	}
+
+	if isRetryableDNSZoneRecordError(cloudError) {
+		details.Classification = core.ErrorRetryable
+	}
+
+	return details, nil
+}
```
Comment (theunrepentantgeek) [inline v2/api/network/customizations/dns_zones_a_record_extension.go:34]: #nit Missing EoLN at EoF

**Review by theunrepentantgeek — APPROVED** [review]
