### PR TITLE
Split resources indexes into groups

### LINKED ISSUE #2997: Improve clarity of documentation for unreleased resources
**Describe the current behavior**

We list resources in our documentation as soon as the relevant PR is merged, well before any release of ASO includes it.
This has resulted in some users attempting, and failing, use the resource. 
See #2989 for one example - it surely has affected other users who simply didn't report it.

**Describe the improvement**
Improve our documentation to make it clearer that the resource hasn't yet been released.

### PR DESCRIPTION
**Pull request by theunrepentantgeek**
**What this PR does / why we need it**:

As the number of supported resources grows, the tables of resources in each group are becoming unwieldy. 

We're also discovering that some users are trying to make use of unreleased resources (e.g. #2989), highlighting that our documentation is not sufficiently clear. 

This PR splits the list of resources for each group into (up to) three sections: _Next Release_, _Released_, and _Deprecated_, with suitable commentary under each.

Closes #2997 

**Special notes for your reviewer**:

Wording is split out into fragments under `/docs/v2/azure/supported-resources` to make it easy to update.

**How does this PR make you feel**:
gif

**If applicable**:
- [x] this PR contains documentation
- [x] this PR contains tests

### CODE REVIEW

File: v2/tools/generator/internal/codegen/pipeline/report_resource_versions.go [hunk 1]
```diff
@@ -307,42 +298,115 @@ func (report *ResourceVersionsReport) WriteGroupResourcesReportToBuffer(
...
+	// Pull out any deprecated resources
+	deprecatedResources := releasedResources.Where(report.isDeprecatedResource)
+	releasedResources = releasedResources.Except(deprecatedResources)
+
+	// Pull out any prerelease resources
+	prereleaseResources := releasedResources.Where(report.isUnreleasedResource)
+	releasedResources = releasedResources.Except(prereleaseResources)
+
+	// First list prerelease reources, if any
+	if len(prereleaseResources) > 0 {
```
Comment (super-harsh) [inline v2/tools/generator/internal/codegen/pipeline/report_resource_versions.go:321]: can consider moving `len(resources) > 0` into the `writeSection` method

**Review by super-harsh — APPROVED** [review]

File: v2/tools/generator/internal/codegen/pipeline/report_resource_versions.go (hunk 1 above)
Comment (theunrepentantgeek) [reply v2/tools/generator/internal/codegen/pipeline/report_resource_versions.go]: Fair call. Done.

File: docs/v2/azure/supported-resources/deprecated.md [hunk 2]
```diff
@@ -0,0 +1 @@
+These resource versions are deprecated and will be removed in an upcoming ASO release. Migration to newer versions is advised. See [Breaking Changes](https://azure.github.io/azure-service-operator/guide/breaking-changes/) for more information.
```
Comment (matthchr) [inline docs/v2/azure/supported-resources/deprecated.md:1]: Where are these files displayed? They seem pretty bare.

Comment (matthchr) [reply docs/v2/azure/supported-resources/deprecated.md:1]: Or are they just injected into the documentation but not actually displayed themselves? If so that makes sense.

File: v2/azure-arm.yaml [hunk 3]
```diff
@@ -31,6 +31,8 @@ supportedResourcesReport:
   # resourcePath is a template used for generating a file path for checking whether docs for a resource have been generated
   # specified relative to the directory of outputPath, and supports the same placeholders
   resourcePathTemplate: "{group}/{version}.md"
+  # latestRelease is the version of our current release (resources introduced in newer releases will be shown as unreleased)
+  latestRelease: v2.0.0
```
Comment (matthchr) [inline v2/azure-arm.yaml:35]: The version is injected into each binary as part of the build process with this cmd from taskfile:
`-ldflags "-X {{.PACKAGE}}/internal/version.BuildVersion={{.VERSION}}"`

You should be able to read the `BuildVersion` variable, which will be of the form `v2.0.0-rev.72`. If you just cut off the "additional stuff" after the `-`, you'll have the most recent release.

That way you don't need to hard-code this, it can be determined dynamically.

File: v2/tools/generator/internal/config/supported_resources_report.go [hunk 4]
```diff
@@ -22,6 +22,8 @@ type SupportedResourcesReport struct {
 	// ResourcePathTemplate is a template used for generating a file path for checking whether docs for a resource have been generated
 	// specified relative to the directory of outputPath
 	ResourcePathTemplate string `yaml:"resourcePathTemplate"`
+	// LatestRelease is the version of the current release. Newer resources will be shown in a separate section.
+	LatestRelease string `yaml:"latestRelease"`
```
Comment (matthchr) [inline v2/tools/generator/internal/config/supported_resources_report.go:26]: As mentioned, this is unneeded you should be able to use the `BuildVersion` variable. Just add a helper in that `internal/version` library that gets the latest released version by parsing the version.

File: docs/v2/azure/supported-resources/deprecated.md (hunk 2 above)
Comment (theunrepentantgeek) [reply docs/v2/azure/supported-resources/deprecated.md:1]: This directory contains fragments that are injected into the generated files where specified.

File: v2/azure-arm.yaml (hunk 3 above)
Comment (super-harsh) [reply v2/azure-arm.yaml:35]: Good point! This way we don't have to hardcode the version manually on each release.

Comment (theunrepentantgeek) [reply v2/azure-arm.yaml:35]: I tried this out - but the variable is only defined when `generator` is build by the `Taskfile` - so it's not available when running tests (e.g. the tests that the report works, nor if you're running the generator by hand. I'm open to making this change, but there seem to be a number of thorns, so I'll push it out to another PR.

Comment (theunrepentantgeek) [reply v2/azure-arm.yaml]: Completed in this PR. Uses `version.BuildVersion` if available, falls back to using `git` commands if not.
