### PR TITLE
Fix bug where the conversion graph wouldn't bridge for resources that skip versions

### LINKED ISSUE #2185: Incorrect conversions generated when resources imported from non-adjacent versions
Instead of importing all resources from each version, we have adopted a surgical approach where we import specified resources only. These may be selected from different versions (the reasons for this are outside the scope of this issue).

For example, returning to the hypothetical CRM service used for many of our specifications, we may import **Person** from one version, **Location** from a second, and **Event** from a third, giving rise to the following conversion graph between versions:

adr-2022-02-crm-version-graph

From this, we generate a set of available conversions between resources (note that each is a subset of the graph above):

adr-2022-02-crm-resource-graphs

When introducing a second version of Person, the current code works correctly if the newly introduced version is adjacent to the previous one:

adr-2022-02-crm-person-graph-valid

But we encounter a previously unanticipated edge case when the newly introduced version is not adjacent:

adr-2022-02-crm-person-graph-invalid

We end up with two hub versions of Person, which is neither correct nor supported.

What we want is for the **Person** conversion graph to correctly link the two available storage versions:

adr-2022-02-crm-person-graph-fixed

### PR DESCRIPTION
**Pull request by theunrepentantgeek**
**What this PR does / why we need it**:

Creation of the conversion graph was incorrectly identifying multiple versions of the same resource as Hub types because it was failing to skip versions where the resource does not exist. See #2185 for more details.

Closes #2185 

**How does this PR make you feel**:
gif

**If applicable**:
- [x] this PR contains tests

### CODE REVIEW

File: v2/tools/generator/internal/codegen/storage/conversion_graph.go [hunk 1]
```diff
@@ -39,77 +39,45 @@ func (graph *ConversionGraph) LookupTransition(ref astmodel.PackageReference) (a
 }
 
 // FindNextType returns the type name of the next closest type on the path to the hub type.
-// Returns the type name and no error if the next type is found; nil and no error if not; nil and an error if something
-// goes wrong.
+// Returns the type name and no error if the next type is found; empty name and no error if not; nil and an error if
```
Comment (babbageclunk) [inline v2/tools/generator/internal/codegen/storage/conversion_graph.go:42]:
```suggestion
// Returns the type name and no error if the next type is found; empty name and no error if not; empty name and an error if
```

**Review by babbageclunk — APPROVED** [review]
Looks good to me!

File: v2/tools/generator/internal/codegen/storage/conversion_graph.go [hunk 2]
```diff
@@ -174,3 +142,83 @@ func (graph *ConversionGraph) FindNextProperty(
...
+	typeName astmodel.TypeName,
+	definitions astmodel.TypeDefinitionSet) (astmodel.TypeName, int) {
+	return graph.searchForMatchingTypeImpl(typeName, definitions, 1)
+}
+
+// searchForMatchingTypeImpl is the recursive implementation of searchForMatchingType.
+func (graph *ConversionGraph) searchForMatchingTypeImpl(
+	typeName astmodel.TypeName,
+	definitions astmodel.TypeDefinitionSet,
+	steps int) (astmodel.TypeName, int) {
```
Comment (matthchr) [inline v2/tools/generator/internal/codegen/storage/conversion_graph.go:209]: really minor: `steps` sorta sounds like it's an instruction on how many steps to use, rather than a "current state". Wondering if it might be clearer as `currentSteps` or something. Obviously this is super minor though.

File: v2/tools/generator/internal/codegen/storage/conversion_graph.go [hunk 3]
```diff
@@ -174,3 +142,83 @@ func (graph *ConversionGraph) FindNextProperty(
...
+	// If we have any error other than a NotConfiguredError, something went wrong, and we must abort
+	if err != nil {
+		return astmodel.EmptyTypeName, -1, errors.Wrapf(
+			err,
+			"finding next type after %s",
+			name)
+	}
+
+	newType := name.WithName(rename)
+	result, steps := graph.searchForMatchingTypeImpl(newType, definitions, 1)
```
Comment (matthchr) [inline v2/tools/generator/internal/codegen/storage/conversion_graph.go:176]: minor: isn't this just `searchForMatchingType(newType, definitions)`?

**Review by matthchr — APPROVED** [review]
LGTM

File: v2/tools/generator/internal/codegen/storage/conversion_graph.go (hunk 2 above)
Comment (theunrepentantgeek) [reply v2/tools/generator/internal/codegen/storage/conversion_graph.go:209]: Renamed to `stepsSoFar`

File: v2/tools/generator/internal/codegen/storage/conversion_graph.go (hunk 3 above)
Comment (theunrepentantgeek) [reply v2/tools/generator/internal/codegen/storage/conversion_graph.go:176]: Yup. Fixed.
