### PR TITLE
Handle SQL DB conflicts (and other errors)

### LINKED ISSUE #1274: Bug: SQL DB reconcile can get stuck due to errors with long-running operation
**Describe the bug**
SQL DBs can get stuck due to certain errors which can happen to their LROs when provisioning.

**To Reproduce**
This is most commonly observed when there are multiple things attempting to manage a single object, as is the case in a multi-cluster setup or if there are manual actions being performed on a SQL Server at the same time the operator is attempting to reconcile a database of that server.

1. Create DB in server s1 with operator deployment 1
2. Create same DB in server s2 with operator deployment 2.

Observe that sometimes the second operator deployment gets an error related to `ConflictingDatabaseOperation`

**Expected behavior**
Resource should properly reconcile.

### PR DESCRIPTION
**Pull request by matthchr**
Closes #1274

**What this PR does / why we need it**:
SQL Databases can sometimes hit an error when attempting to modify them in quick succession. This can happen for a variety of reasons but is common in situations where there are multiple managers reconciling against the same Azure resource. Before this fix when this happened the DB would just get stuck forever.

This PR fixes the above issues and allows the operator to retry when this problem occurs.

**Special notes for your reviewer**:
This issue is difficult to write a test for given the current test framework. We should spend some time improving the framework to allow for this sort of test (probably after generator lands?)

### CODE REVIEW

File: pkg/errhelp/errors.go [hunk 1]
```diff
@@ -148,6 +149,9 @@ func NewAzureError(err error) error {
 }
 
 func NewAzureErrorAzureError(err error) *AzureError {
+	if err == nil {
```
Comment (babbageclunk) [inline pkg/errhelp/errors.go:152]: Nice. The name of this totally threw me but I can see why it's like that.

File: pkg/resourcemanager/azuresql/azuresqldb/azuresqldb_reconcile.go [hunk 2]
```diff
@@ -68,9 +68,15 @@ func (db *AzureSqlDbManager) Ensure(ctx context.Context, obj runtime.Object, opt
 
 	// Before we attempt to issue a new update, check if there is a previously ongoing update
 	if instance.Status.PollingURL != "" {
+		// TODO: There are other places which use PollClient which may or may not need this treatment as well...
 		pClient := pollclient.NewPollClient()
 		res, err := pClient.Get(ctx, instance.Status.PollingURL)
-		if err != nil {
+		pollErr := errhelp.NewAzureErrorAzureError(err)
```
Comment (babbageclunk) [inline pkg/resourcemanager/azuresql/azuresqldb/azuresqldb_reconcile.go:74]: Can Get ever return a non-AzureError error error?

**Review by babbageclunk — APPROVED** [review]

File: pkg/resourcemanager/azuresql/azuresqldb/azuresqldb_reconcile.go (hunk 2 above)
Comment (matthchr) [reply pkg/resourcemanager/azuresql/azuresqldb/azuresqldb_reconcile.go:74]: The way `NewAzureErrorAzureError` is written, even if the error doesn't match one of the predefined types it does its best to match what it can, so it won't blow up.

I don't think that get will return anything other than `autorest.DetailedError` (which is what `NewAzureErrorAzureError` parses), and there are other places in the code where I see `NewAzureErrorAzureError` has been used on the result of a call to the polling client... so I think we're ok here.

Comment (babbageclunk) [reply pkg/resourcemanager/azuresql/azuresqldb/azuresqldb_reconcile.go:74]: That makes sense - thanks for the extra detail!

File: pkg/errhelp/errors.go (hunk 1 above)
Comment (theunrepentantgeek) [reply pkg/errhelp/errors.go:152]: The name _completely_ mystifies me - and I've spent 15m looking at this and the use of it to try and get my head around it.

At minimum, it needs a comment to explain what it does; better if it's given a name that actually expresses what it does.

Comment (theunrepentantgeek) [reply pkg/errhelp/errors.go:152]: Given other Go code that accepts `error` and returns something else, maybe the name needs to start with `Wrap`?

**Review by theunrepentantgeek — CHANGES_REQUESTED** [review]

File: pkg/errhelp/errors.go (hunk 1 above)
Comment (matthchr) [reply pkg/errhelp/errors.go:152]: I've renamed this to `NewAzureError` and combined this and the existing `NewAzureError` since there's no reason to have the method that returns error (since `*AzureError` impls it anyway).

**Review by theunrepentantgeek — APPROVED** [review]
Thanks for renaming that method, makes more sense now. Approved!
