### PR TITLE
Move 'batch' to use hybrid versioning

### LINKED ISSUE #5113: Bug: Import alias assignment fails in generator
## Describe the bug

When moving `batch` to _hybrid_ versioning mode, I discovered that we were generating uncompilable code like this:

``` go
import (
	"github.com/Azure/azure-service-operator/v2/api/batch/v1api20210101"
	"github.com/Azure/azure-service-operator/v2/api/batch/v1api20210101/storage"
	"github.com/Azure/azure-service-operator/v2/api/batch/v20210101"
	"github.com/Azure/azure-service-operator/v2/api/batch/v20210101/storage"
	"github.com/Azure/azure-service-operator/v2/api/batch/v20240701"
	"github.com/Azure/azure-service-operator/v2/api/batch/v20240701/storage"
	"github.com/Azure/azure-service-operator/v2/pkg/genruntime"
)
```

While all the import paths are distinct, three of them would be referenced as `storage`, and the Go compiler naturally objects.

Digging into the underlying issue, I identified two problems.

Firstly, alias assignment in `PackageImportSet.assignImportAliases()` is silently failing.

Secondly, all our existing alias naming styles would generate conflicts:

| Import                                  | Name          | GroupOnly  | VersionOnly    | GroupAndVersion      |
| --------------------------------------- | ------------- | ---------- | -------------- | -------------------- |
| ... v2/api/batch/v1api20210101"         | v1api20210101 | **batch**  | **v20210101s** | **batch_v20210101s** |
| ... v2/api/batch/v1api20210101/storage" | **storage**   | **batch**  | **v20210101s** | **batch_v20210101s** |
| ... v2/api/batch/v20210101"             | v20210101     | **batch**  | **v20210101**  | **batch_v20210101**  |
| ... v2/api/batch/v20210101/storage"     | **storage**   | **batch**  | **v20210101s** | **batch_v20210101**  |
| ... v2/api/batch/v20240701"             | v20240701     | **batch**  | v20240701      | batch_v20240701      |
| ... v2/api/batch/v20240701/storage"     | **storage**   | **batch**  | v20240701s     | batch_v20240701s     |
| ... v2/pkg/genruntime"                  | genruntime    | genruntime | genruntime     | genruntime           |

Columns demonstrate our supported naming styles, bold indicates conflicts.

## Expected behavior

Each import should be assigned a distinct alias.

## To Reproduce

Check out `main` (`698a65f6a8`), modify `legacy.go` to move the group to `Hybrid` versioning, then run a build.

### PR DESCRIPTION
**Pull request by theunrepentantgeek**
## What this PR does

As a part of #4831, moves the `batch` group to Hybrid mode, where all resources are available with the new style `v` versioning, and older resources remain available with `v1api` style versioning.

Also addresses a bug with import alias selection in our code generator.

Fixes #5113

## How does this PR make you feel?

gif

## Checklist

- [x] this PR contains tests
- [x] this PR contains YAML Samples

### CODE REVIEW

File: v2/tools/generator/internal/astmodel/package_import_style.go [hunk 1]
```diff
@@ -11,10 +11,16 @@ type PackageImportStyle string
...
 	// VersionOnly is used when using just the version of the package is sufficiently unique
 	VersionOnly PackageImportStyle = "VersionOnly"
+
 	// GroupOnly is used when using just the group of the package sufficiently unique
 	GroupOnly PackageImportStyle = "GroupOnly"
+
 	// GroupAndVersion is used when both the group and version of the package are required for it to be unique
 	GroupAndVersion PackageImportStyle = "GroupAndVersion"
+
+	// GroupAndFullVersion is a fallback for when more concise styles are not unique enough
```
Comment (matthchr) [inline v2/tools/generator/internal/astmodel/package_import_style.go]: minor: Clarify what is the difference between a "full version" and a "version"?

File: v2/tools/generator/internal/astmodel/local_package_reference.go [hunk 2]
```diff
@@ -174,6 +174,12 @@ func (pr LocalPackageReference) ImportAlias(style PackageImportStyle) string {
 			groupForAlias,
 			pr.simplifiedGeneratorVersion(pr.generatorVersion),
 			pr.simplifiedAPIVersion(pr.apiVersion))
+	case GroupAndFullVersion:
+		return fmt.Sprintf(
+			"%s_%s%s",
```
Comment (matthchr) [inline v2/tools/generator/internal/astmodel/local_package_reference.go:181]: Possibly came up before and I just don't remember, but did we try to come up with a way to avoid `_` in aliases? AFAIK it's not amazingly standard for go pkg aliases to have `_`'s

Comment (theunrepentantgeek) [reply v2/tools/generator/internal/astmodel/local_package_reference.go:181]: It comes down to readability - we often see these aliases in groups where the only difference is the version number.

I've added some comments in `local_package_reference.go`.

File: v2/tools/generator/internal/astmodel/package_import_style.go (hunk 1 above)
Comment (theunrepentantgeek) [reply v2/tools/generator/internal/astmodel/package_import_style.go]: We normally abbreviate the prefix `v1api` as simply `v` to make the aliases easier to read; a full version doesn't do this. I've added comments and cross references to the code.

**Review by matthchr — APPROVED** [review]
